sonar.projectKey=apchavez_azure-python
sonar.projectName=azure-python
sonar.organization=apchavez
sonar.sources=clinic,function_app.py
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/generated/**
sonar.coverage.exclusions=clinic/infrastructure/**,function_app.py
